const names = {
    // 임시
    "seoul": "서울시",
    "busan": "부산시",
    "gijang": "기장군",
    "daegu": "대구시",
    "dalseong": "달성군",
    "gunwi": "군위군",
    "incheon": "인천시",
    "ganghwa": "강화군",
    "ongjin": "옹진군",
    "gwangju": "광주시",
    "daejeon": "대전시",
    "ulsan": "울산시",
    "ulju": "울주군",
    "sejong": "세종시",
    "jeju": "제주시",
    "seogwipo": "서귀포시",
    "gangneung": "강릉시",
    "donghae": "동해시",
    "samcheok": "삼척시",
    "sokcho": "속초시",
    "wonju": "원주시",
    "chuncheon": "춘천시",
    "taebaek": "태백시",
    "ganseong": "고성군",
    "yanggu": "양구군",
    "yangyang": "양양군",
    "yeongwol": "영월군",
    "inje": "인제군",
    "jeongseon": "정선군",
    "cheorwon": "철원군",
    "pyeongchang": "평창군",
    "hongcheon": "홍천군",
    "hwacheon": "화천군",
    "hoengseong": "횡성군",
    "gimhwa": "김화군",
    "icheongw": "이천군",
    "tongcheon": "통천군",
    "pyeonggang": "평강군",
    "hoeyang": "회양군",
    "changwon": "창원시",
    "geoje": "거제시",
    "gimhae": "김해시",
    "miryang": "밀양시",
    "sacheon": "사천시",
    "yangsan": "양산시",
    "jinju": "진주시",
    "tongyeong": "통영시",
    "geochang": "거창군",
    "goseong": "고성군",
    "namhae": "남해군",
    "sancheong": "산청군",
    "uiryeong": "의령군",
    "changnyeong": "창녕군",
    "hadong": "하동군",
    "haman": "함안군",
    "hamyang": "함양군",
    "hapcheon": "합천군",
    "jecheon": "제천시",
    "cheongju": "청주시",
    "chungju": "충주시",
    "goesan": "괴산군",
    "danyang": "단양군",
    "boeun": "보은군",
    "yeongdong": "영동군",
    "okcheon": "옥천군",
    "eumseong": "음성군",
    "jeungpyeong": "증평군",
    "jincheon": "진천군",
    "goyang": "고양시",
    "suwon": "수원시",
    "yongin": "용인시",
    "gwacheon": "과천시",
    "gwangmyeong": "광명시",
    "gyeongan": "광주시",
    "guri": "구리시",
    "gunpo": "군포시",
    "gimpo": "김포시",
    "namyangju": "남양주시",
    "dongducheon": "동두천시",
    "bucheon": "부천시",
    "seongnam": "성남시",
    "siheung": "시흥시",
    "ansan": "안산시",
    "anseong": "안성시",
    "anyang": "안양시",
    "yangju": "양주시",
    "yeoju": "여주시",
    "osan": "오산시",
    "uiwang": "의왕시",
    "uijeongbu": "의정부시",
    "icheon": "이천시",
    "paju": "파주시",
    "pyeongtaek": "평택시",
    "pocheon": "포천시",
    "hanam": "하남시",
    "hwaseong": "화성시",
    "gapyeong": "가평군",
    "yangpyeong": "양평군",
    "yeoncheon": "연천군",
    "gaeseong": "개성시",
    "gaepung": "개풍군",
    "jangdan": "장단군",
    "gyeongsan": "경산시",
    "gyeongju": "경주시",
    "gumi": "구미시",
    "gimcheon": "김천시",
    "mungyeong": "문경시",
    "sangju": "상주시",
    "andong": "안동시",
    "yeongju": "영주시",
    "yeongcheon": "영천시",
    "pohang": "포항시",
    "goryeong": "고령군",
    "bonghwa": "봉화군",
    "seongju": "성주군",
    "yeongdeok": "영덕군",
    "yeongyang": "영양군",
    "yecheon": "예천군",
    "ulleung": "울릉군",
    "uljin": "울진군",
    "uiseong": "의성군",
    "cheongdo": "청도군",
    "cheongsong": "청송군",
    "chilgok": "칠곡군",
    "gyeryong": "계룡시",
    "gongju": "공주시",
    "nonsan": "논산시",
    "dangjin": "당진시",
    "boryeong": "보령시",
    "seosan": "서산시",
    "asan": "아산시",
    "cheonan": "천안시",
    "geumsan": "금산군",
    "buyeo": "부여군",
    "seocheon": "서천군",
    "yesan": "예산군",
    "cheongyang": "청양군",
    "taean": "태안군",
    "hongseong": "홍성군",
    "gunsan": "군산시",
    "gimje": "김제시",
    "namwon": "남원시",
    "iksan": "익산시",
    "jeonju": "전주시",
    "jeongeup": "정읍시",
    "gochang": "고창군",
    "muju": "무주군",
    "buan": "부안군",
    "sunchang": "순창군",
    "wanju": "완주군",
    "imsil": "임실군",
    "jangsu": "장수군",
    "jinan": "진안군",
    "mokpo": "목포시",
    "yeosu": "여수시",
    "suncheon": "순천시",
    "naju": "나주시",
    "gwangyang": "광양시",
    "damyang": "담양군",
    "gokseong": "곡성군",
    "gurye": "구례군",
    "goheung": "고흥군",
    "boseong": "보성군",
    "hwasun": "화순군",
    "jangheung": "장흥군",
    "gangjin": "강진군",
    "haenam": "해남군",
    "yeongam": "영암군",
    "muan": "무안군",
    "hampyeong": "함평군",
    "yeonggwang": "영광군",
    "jangseong": "장성군",
    "wando": "완도군",
    "jindo": "진도군",
    "sinan": "신안군",

    // 서울시
    "SEO_PROV_SEOUL": "서울시",
    "SEO_CITY_SEOUL": "서울시",
    "SEO_DISTRICT_JONGNO": "종로구",
    "SEO_DISTRICT_CENTRAL": "중구",
    "SEO_DISTRICT_YONGSAN": "용산구",
    "SEO_DISTRICT_SEONGDONG": "성동구",
    "SEO_DISTRICT_GWANGJIN": "광진구",
    "SEO_DISTRICT_DONGDAEMUN": "동대문구",
    "SEO_DISTRICT_JUNGNANG": "중랑구",
    "SEO_DISTRICT_SEONGBUK": "성북구",
    "SEO_DISTRICT_GANGBUK": "강북구",
    "SEO_DISTRICT_DOBONG": "도봉구",
    "SEO_DISTRICT_NOWON": "노원구",
    "SEO_DISTRICT_EUNPYEONG": "은평구",
    "SEO_DISTRICT_SEODAEMUN": "서대문구",
    "SEO_DISTRICT_MAPO": "마포구",
    "SEO_DISTRICT_YANGCHEON": "양천구",
    "SEO_DISTRICT_GANGSEO": "강서구",
    "SEO_DISTRICT_GURO": "구로구",
    "SEO_DISTRICT_GEUMCHEON": "금천구",
    "SEO_DISTRICT_YEONGDEUNGPO": "영등포구",
    "SEO_DISTRICT_DONGJAK": "동작구",
    "SEO_DISTRICT_GWANAK": "관악구",
    "SEO_DISTRICT_SEOCHO": "서초구",
    "SEO_DISTRICT_GANGNAM": "강남구",
    "SEO_DISTRICT_SONGPA": "송파구",
    "SEO_DISTRICT_GANGDONG": "강동구",

    // 부산시
    "BUS_PROV_BUSAN": "부산시",
    "BUS_CITY_BUSAN": "부산시",
    "BUS_DISTIRCT_CENTRAL": "중구",
    "BUS_DISTRICT_WESTERN": "서구",
    "BUS_DISTRICT_EASTERN": "동구",
    "BUS_DISTRICT_YEONGDO": "영도구",
    "BUS_DISTRICT_BUSANJIN": "부산진구",
    "BUS_DISTRICT_DONGNAE": "동래구",
    "BUS_DISTRICT_SOUTHERN": "남구",
    "BUS_DISTRICT_NORTHERN": "북구",
    "BUS_DISTRICT_HAEUNDAE": "해운대구",
    "BUS_DISTRICT_SAHA": "사하구",
    "BUS_DISTRICT_GEUMJEONG": "금정구",
    "BUS_DISTRICT_GANGSEO": "강서구",
    "BUS_DISTRICT_YEONJE": "연제구",
    "BUS_DISTRICT_SUYEONG": "수영구",
    "BUS_DISTRICT_SASANG": "사상구",
    "BUS_COUNTY_GIJANG": "기장군",

    // 대구시
    "DAE_PROV_DAEGU": "대구시",
    "DAE_CITY_DAEGU": "대구시",
    "DAE_DISTRICT_CENTRAL": "중구",
    "DAE_DISTRICT_EASTERN": "동구",
    "DAE_DISTRICT_WESTERN": "서구",
    "DAE_DISTRICT_SOUTHERN": "남구",
    "DAE_DISTRICT_NORTHERN": "북구",
    "DAE_DISTRICT_SUSEONG": "수성구",
    "DAE_DISTRICT_DALSEO": "달서구",
    "DAE_COUNTY_DALSEONG": "달성군",
    "DAE_COUNTY_GUNWI": "군위군",

    // 인천시
    "INC_PROV_INCHEON": "인천시",
    "INC_CITY_INCHEON": "인천시",
    "INC_DISTRICT_CENTRAL": "중구",
    "INC_DISTRICT_EASTERN": "동구",
    "INC_DISTRICT_MICHUHOL": "미추홀구",
    "INC_DISTRICT_YEONSU": "연수구",
    "INC_DISTRICT_NAMDONG": "남동구",
    "INC_DISTRICT_BUPYEONG": "부평구",
    "INC_DISTRICT_GYEYANG": "계양구",
    "INC_DISTRICT_WESTERN": "서구",
    "INC_COUNTY_GANGHWA": "강화군",
    "INC_COUNTY_ONGJIN": "옹진군",

    // 광주시
    "GWJ_PROV_GWANGJU": "광주시",
    "GWJ_CITY_GWANGJU": "광주시",
    "GWJ_DISTRICT_EASTERN": "동구",
    "GWJ_DISTRICT_WESTERN": "서구",
    "GWJ_DISTRICT_SOUTHERN": "남구",
    "GWJ_DISTRICT_NORTHERN": "북구",
    "GWJ_DISTRICT_GWANGSAN": "광산구",

    // 대전시
    "DJN_PROV_DAEJEON": "대전시",
    "DJN_CITY_DAEJEON": "대전시",
    "DJN_DISTRICT_EASTERN": "동구",
    "DJN_DISTRICT_CENTRAL": "중구",
    "DJN_DISTRICT_WESTERN": "동구",
    "DJN_DISTRICT_YUSEONG": "유성구",
    "DJN_DISTRICT_DAEDEOK": "대덕구",

    // 울산시
    "ULS_PROV_ULSAN": "울산시",
    "ULS_CITY_ULSAN": "울산시",
    "ULS_DISTRICT_CENTRAL": "중구",
    "ULS_DISTRICT_SOUTHERN": "남구",
    "ULS_DISTRICT_EASTERN": "동구",
    "ULS_DISTRICT_NORTHERN": "북구",
    "ULS_COUNTY_ULJU": "울주군",

    // 세종시
    "SEJ_PROV_SEJONG": "세종시",
    "SEJ_CITY_SEJONG": "세종시",

    // 경기도
    "SGG_PROV_GYEONGGI": "경기도",
    "SGG_CITY_GOYANG": "고양시",
    "SGG_CITY_SUWON": "수원시",
    "SGG_CITY_YONGIN": "용인시",
    "SGG_CITY_GWACHEON": "과천시",
    "SGG_CITY_GWANGMYEONG": "광명시",
    "SGG_CITY_GWANGJU": "광주시",
    "SGG_CITY_GURI": "구리시",
    "SGG_CITY_GUNPO": "군포시",
    "SGG_CITY_GIMPO": "김포시",
    "SGG_CITY_NAMYANGJU": "남양주시",
    "SGG_CITY_DONGDUCHEON": "동두천시",
    "SGG_CITY_BUCHEON": "부천시",
    "SGG_CITY_SEONGNAM": "성남시",
    "SGG_CITY_SIHEUNG": "시흥시",
    "SGG_CITY_ANSAN": "안산시",
    "SGG_CITY_ANSEONG": "안성시",
    "SGG_CITY_ANYANG": "안양시",
    "SGG_CITY_YANGJU": "양주시",
    "SGG_CITY_YEOJU": "여주시",
    "SGG_CITY_OSAN": "오산시",
    "SGG_CITY_UIWANG": "의왕시",
    "SGG_CITY_UIJEONGBU": "의정부시",
    "SGG_CITY_ICHEON": "이천시",
    "SGG_CITY_PAJU": "파주시",
    "SGG_CITY_PYEONGTAEK": "평택시",
    "SGG_CITY_POCHEON": "포천시",
    "SGG_CITY_HANAM": "하남시",
    "SGG_CITY_HWASEONG": "화성시",
    "SGG_COUNTY_GAPYEONG": "가평군",
    "SGG_COUNTY_YANGPYEONG": "양평군",
    "SGG_COUNTY_YEONCHEON": "연천군",
    "SGG_CITY_GAESEONG": "개성시",
    "SGG_COUNTY_GAEPUNG": "개풍군",
    "SGG_COUNTY_JANGDAN": "장단군",

    // 충청북도
    "NCC_PROV_NORTHCHUNGCHEONG": "충청북도",
    "NCC_CITY_JECHEON": "제천시",
    "NCC_CITY_CHEONGJU": "청주시",
    "NCC_CITY_CHUNGJU": "충주시",
    "NCC_COUNTY_GOESAN": "괴산군",
    "NCC_COUNTY_DANYANG": "단양군",
    "NCC_COUNTY_BOEUN": "보은군",
    "NCC_COUNTY_YEONGDONG": "영동군",
    "NCC_COUNTY_OKCHEON": "옥천군",
    "NCC_COUNTY_EUMSEONG": "음성군",
    "NCC_COUNTY_JEUNGPYEONG": "증평군",
    "NCC_COUNTY_JINCHEON": "진천군",

    // 충청남도
    "SCC_PROV_SOUTHCHUNGCHEONG": "충청남도",
    "SCC_CITY_GYERYONG": "계룡시",
    "SCC_CITY_GONGJU": "공주시",
    "SCC_CITY_NONSAN": "논산시",
    "SCC_CITY_DANGJIN": "당진시",
    "SCC_CITY_BORYEONG": "보령시",
    "SCC_CITY_SEOSAN": "서산시",
    "SCC_CITY_ASAN": "아산시",
    "SCC_CITY_CHEONAN": "천안시",
    "SCC_COUNTY_GEUMSAN": "금산군",
    "SCC_COUNTY_BUYEO": "부여군",
    "SCC_COUNTY_SEOCHEON": "서천군",
    "SCC_COUNTY_YESAN": "예산군",
    "SCC_COUNTY_CHEONGYANG": "청양군",
    "SCC_COUNTY_TAEAN": "태안군",
    "SCC_COUNTY_HONGSEONG": "홍성군",

    // 전라북도
    "NJE_PROV_NORTHJEOLLA": "전라북도",
    "NJE_CITY_GUNSAN": "군산시",
    "NJE_CITY_GIMJE": "김제시",
    "NJE_CITY_NAMWON": "남원시",
    "NJE_CITY_IKSAN": "익산시",
    "NJE_CITY_JEONJU": "전주시",
    "NJE_CITY_JEONGEUP": "정읍시",
    "NJE_COUNTY_GOCHANG": "고창군",
    "NJE_COUNTY_MUJU": "무주군",
    "NJE_COUNTY_BUAN": "부안군",
    "NJE_COUNTY_SUNCHANG": "순창군",
    "NJE_COUNTY_WANJU": "완주군",
    "NJE_COUNTY_IMSIL": "임실군",
    "NJE_COUNTY_JANGSU": "장수군",
    "NJE_COUNTY_JINAN": "진안군",

    // 전라남도
    "SJE_PROV_SOUTHJEOLLA": "전라남도",
    "SJE_CITY_MOKPO": "목포시",
    "SJE_CITY_YEOSU": "여수시",
    "SJE_CITY_SUNCHEON": "순천시",
    "SJE_CITY_NAJU": "나주시",
    "SJE_CITY_GWANGYANG": "광양시",
    "SJE_COUNTY_DAMYANG": "담양군",
    "SJE_COUNTY_GOKSEONG": "곡성군",
    "SJE_COUNTY_GURYE": "구례군",
    "SJE_COUNTY_GOHEUNG": "고흥군",
    "SJE_COUNTY_BOSEONG": "보성군",
    "SJE_COUNTY_HWASUN": "화순군",
    "SJE_COUNTY_JANGHEUNG": "장흥군",
    "SJE_COUNTY_GANGJIN": "강진군",
    "SJE_COUNTY_HAENAM": "해남군",
    "SJE_COUNTY_YEONGAM": "영암군",
    "SJE_COUNTY_MUAN": "무안군",
    "SJE_COUNTY_HAMPYEONG": "함평군",
    "SJE_COUNTY_YEONGGWANG": "영광군",
    "SJE_COUNTY_JANGSEONG": "장성군",
    "SJE_COUNTY_WANDO": "완도군",
    "SJE_COUNTY_JINDO": "진도군",
    "SJE_COUNTY_SINAN": "신안군",

    // 경상북도
    "NGS_PROV_NORTHGYEONGSANG": "경상북도",
    "NGS_CITY_GYEONGSAN": "경산시",
    "NGS_CITY_GYEONGJU": "경주시",
    "NGS_CITY_GUMI": "구미시",
    "NGS_CITY_GIMCHEON": "김천시",
    "NGS_CITY_MUNGYEONG": "문경시",
    "NGS_CITY_SANGJU": "상주시",
    "NGS_CITY_ANDONG": "안동시",
    "NGS_CITY_YEONGJU": "영주시",
    "NGS_CITY_YEONGCHEON": "영천시",
    "NGS_CITY_POHANG": "포항시",
    "NGS_COUNTY_GORYEONG": "고령군",
    "NGS_COUNTY_BONGHWA": "봉화군",
    "NGS_COUNTY_SEONGJU": "성주군",
    "NGS_COUNTY_YEONGDEOK": "영덕군",
    "NGS_COUNTY_YEONGYANG": "영양군",
    "NGS_COUNTY_YECHEON": "예천군",
    "NGS_COUNTY_ULLEUNG": "울릉군",
    "NGS_COUNTY_ULJIN": "울진군",
    "NGS_COUNTY_UISEONG": "의성군",
    "NGS_COUNTY_CHEONGDO": "청도군",
    "NGS_COUNTY_CHEONGSONG": "청송군",
    "NGS_COUNTY_CHILGOK": "칠곡군",

    // 경상남도
    "SGS_PROV_SOUTHGYEONGSANG": "경상남도",
    "SGS_CITY_CHANGWON": "창원시",
    "SGS_CITY_GEOJE": "거제시",
    "SGS_CITY_GIMHAE": "김해시",
    "SGS_CITY_MIRYANG": "밀양시",
    "SGS_CITY_SACHEON": "사천시",
    "SGS_CITY_YANGSAN": "양산시",
    "SGS_CITY_JINJU": "진주시",
    "SGS_CITY_TONGYEONG": "통영시",
    "SGS_COUNTY_GEOCHANG": "거창군",
    "SGS_COUNTY_GOSEONG": "고성군",
    "SGS_COUNTY_NAMHAE": "남해군",
    "SGS_COUNTY_SANCHEONG": "산청군",
    "SGS_COUNTY_UIRYEONG": "의령군",
    "SGS_COUNTY_CHANGNYEONG": "창녕군",
    "SGS_COUNTY_HADONG": "하동군",
    "SGS_COUNTY_HAMAN": "함안군",
    "SGS_COUNTY_HAMYANG": "함양군",
    "SGS_COUNTY_HAPCHEON": "합천군",

    // 강원도
    "GWN_PROV_GANGWON": "강원도",
    "GWN_CITY_GANGNEUNG": "강릉시",
    "GWN_CITY_DONGHAE": "동해시",
    "GWN_CITY_SAMCHEOK": "삼척시",
    "GWN_CITY_SOKCHO": "속초시",
    "GWN_CITY_WONJU": "원주시",
    "GWN_CITY_CHUNCHEON": "춘천시",
    "GWN_CITY_TAEBAEK": "태백시",
    "GWN_COUNTY_GOSEONG": "고성군",
    "GWN_COUNTY_YANGGU": "양구군",
    "GWN_COUNTY_YANGYANG": "양양군",
    "GWN_COUNTY_YEONGWOL": "영월군",
    "GWN_COUNTY_INJE": "인제군",
    "GWN_COUNTY_JEONGSEON": "정선군",
    "GWN_COUNTY_CHEORWON": "철원군",
    "GWN_COUNTY_PYEONGCHANG": "평창군",
    "GWN_COUNTY_HONGCHEON": "홍천군",
    "GWN_COUNTY_HWACHEON": "화천군",
    "GWN_COUNTY_HOENGSEONG": "횡성군",
    "GWN_COUNTY_GIMHWA": "김화군",
    "GWN_COUNTY_ICHEON": "이천군",
    "GWN_COUNTY_TONGCHEON": "통천군",
    "GWN_COUNTY_PYEONGGANG": "평강군",
    "GWN_COUNTY_HOEYANG": "회양군",

    // 제주도
    "JJU_PROV_JEJU": "제주도",
    "JJU_CITY_JEJU": "제주시",
    "JJU_CITY_SEOGWIPO": "서귀포시",
    "JJU_XCITY_JEJU": "제주시",
    "JJU_XCITY_SEOGWIPO": "서귀포시",
    "JJU_XCOUNTY_NORTHJEJU": "북제주군",
    "JJU_XCOUNTY_SOUTHJEJU": "남제주군",

    // 황해도
    "HWA_PROV_HWANGHAE": "황해도",
    "HWA_CITY_HAEJU": "해주시",
    "HWA_CITY_SARIWON": "사리원시",
    "HWA_CITY_SONGNIM": "송림시",
    "HWA_COUNTY_BYEOKSEONG": "벽성군",
    "HWA_COUNTY_YEONBAEK": "연백군",
    "HWA_COUNTY_GEUMCHEON": "금천군",
    "HWA_COUNTY_PYEONGSAN": "평산군",
    "HWA_COUNTY_SINGYE": "신계군",
    "HWA_COUNTY_JANGYEON": "장연군",
    "HWA_COUNTY_SONGHWA": "송화군",
    "HWA_COUNTY_EUNYUL": "은율군",
    "HWA_COUNTY_ANAK": "안악군",
    "HWA_COUNTY_SINCHEON": "신천군",
    "HWA_COUNTY_JAERYEONG": "재령군",
    "HWA_COUNTY_HWANGJU": "황주군",
    "HWA_COUNTY_BONGSAN": "봉산군",
    "HWA_COUNTY_SEOHEUNG": "서흥군",
    "HWA_COUNTY_SUAN": "수안군",
    "HWA_COUNTY_GOKSAN": "곡산군",
    "HWA_COUNTY_ONGJIN": "옹진군",

    // 평안북도
    "NPY_PROV_NORTHPYEONGAN": "평안북도",
    "NPY_CITY_SINUIJU": "신의주시",
    "NPY_COUNTY_EUIJU": "의주군",
    "NPY_COUNTY_YONGCHEON": "용천군",
    "NPY_COUNTY_CHEOLSAN": "철산군",
    "NPY_COUNTY_SEONCHEON": "선천군",
    "NPY_COUNTY_GANGGYE": "강계군",
    "NPY_COUNTY_JEONGJU": "정주군",
    "NPY_COUNTY_BAKCHEON": "박천군",
    "NPY_COUNTY_TAECHEON": "태천군",
    "NPY_COUNTY_YEONGBYEON": "영변군",
    "NPY_COUNTY_JASEONG": "자성군",
    "NPY_COUNTY_UNSAN": "운산군",
    "NPY_COUNTY_GUSEONG": "구성군",
    "NPY_COUNTY_CHANGSEONG": "창성군",
    "NPY_COUNTY_BYEOKDONG": "벽동군",
    "NPY_COUNTY_HUCHANG": "후창군",
    "NPY_COUNTY_SAKJU": "삭주군",
    "NPY_COUNTY_CHOSAN": "초산군",
    "NPY_COUNTY_WIWON": "위원군",
    "NPY_COUNTY_HUICHEON": "희천군",

    // 평안남도
    "SPY_PROV_SOUTHPYEONGAN": "평안남도",
    "SPY_CITY_PYEONGYANG": "평양시",
    "SPY_CITY_JINNAMPO": "진남포시",
    "SPY_COUNTY_DAEDONG": "대동군",
    "SPY_COUNTY_SUNCHEON": "순천군",
    "SPY_COUNTY_MAENGSAN": "맹산군",
    "SPY_COUNTY_YANGDEOK": "양덕군",
    "SPY_COUNTY_DEOKCHEON": "덕천군",
    "SPY_COUNTY_SEONGCHEON": "성천군",
    "SPY_COUNTY_GANGDONG": "강동군",
    "SPY_COUNTY_JUNGHWA": "중화군",
    "SPY_COUNTY_YONGGANG": "용강군",
    "SPY_COUNTY_YEONGWON": "영원군",
    "SPY_COUNTY_GANGSEO": "강서군",
    "SPY_COUNTY_PYEONGWON": "평원군",
    "SPY_COUNTY_ANJU": "안주군",
    "SPY_COUNTY_GAECHEON": "개천군",

    // 함경북도
    "NHG_PROV_NORTHHAMGYEONG": "함경북도",
    "NHG_CITY_CHEONGJIN": "청진시",
    "NHG_CITY_SEONGJIN": "성진시",
    "NHG_CITY_NAJIN": "나진시",
    "NHG_COUNTY_GYEONGSEONG": "경성군",
    "NHG_COUNTY_MYEONGCHEON": "명천군",
    "NHG_COUNTY_GILJU": "길주군",
    "NHG_COUNTY_HAKSEONG": "학성군",
    "NHG_COUNTY_BURYEONG": "부령군",
    "NHG_COUNTY_MUSAN": "무산군",
    "NHG_COUNTY_HOERYEONG": "회령군",
    "NHG_COUNTY_JONGSEONG": "종성군",
    "NHG_COUNTY_GYEONGHEUNG": "경흥군",
    "NHG_COUNTY_GYEONGWON": "경원군",
    "NHG_COUNTY_ONSEONG": "온성군",

    // 함경남도
    "SHG_PROV_SOUTHHAMGYEONG": "함경남도",
    "SHG_CITY_HAMHEUNG": "함흥시",
    "SHG_CITY_WONSAN": "원산시",
    "SHG_CITY_HEUNGNAM": "흥남시",
    "SHG_COUNTY_HAMJU": "함주군",
    "SHG_COUNTY_JEONGPYEONG": "정평군",
    "SHG_COUNTY_YEONGHEUNG": "영흥군",
    "SHG_COUNTY_GOWON": "고원군",
    "SHG_COUNTY_MUNCHEON": "문천군",
    "SHG_COUNTY_ANBYEONG": "안변군",
    "SHG_COUNTY_HONGWON": "홍원군",
    "SHG_COUNTY_BUKCHEONG": "북청군",
    "SHG_COUNTY_IWON": "이원군",
    "SHG_COUNTY_DANCHEON": "단천군",
    "SHG_COUNTY_SINHEUNG": "신흥군",
    "SHG_COUNTY_JANGJIN": "장진군",
    "SHG_COUNTY_PUNGSAN": "풍산군",
    "SHG_COUNTY_SAMSU": "삼수군",
    "SHG_COUNTY_GAPSAN": "갑산군",
    "SHG_COUNTY_HYESAN": "혜산군"
};

const nameTitle = document.querySelector("#name");
const debugInput = document.querySelector("#debug_input");

console.log(document.querySelector(".area"));

document.querySelectorAll(".area").forEach(x => {
    x.addEventListener("mouseover", () => {
        nameTitle.innerText = names[x.id] ? names[x.id] : x.id;
    });
});


// 디버깅용
const doCheckCode = () => {
    const x = debugInput.value;
    nameTitle.innerText = names[x] ? names[x] : x;
};

document.onkeydown = x => {
    if (debugInput === document.activeElement && x.keyCode === 13) {
        doCheckCode();
    };
};


// 초기화
document.querySelectorAll(".area").forEach(x => {
    x.value = "0";
    x.addEventListener("click", () => {
        doChangeColor(x);
    });
});

const color = {
    0: "white",
    1: "yellow",
    2: "orange",
    3: "hotpink",
    4: "red"
};

const doChangeColor = (x) => {
    const i = parseInt(x.value);
    x.value = ( i >= Object.values(color).length - 1? 0 : i + 1 );
    console.log(x.value);
    x.style.fill = color[x.value];
};